[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
navguard = "7yEjSCMnrDevpu3ASWs2FG41hDHDgTe6NbdaDQZaZmzB"
reference_vault = "DZ5ebhqi5d84jj7atH1X6vX5KZZzH2gvb4PvEhZreD2R"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
